name: flash_cards
description: FlashCards app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0
dependencies:
  states_rebuilder: ^6.4.0
  forui: ^0.15.1
  colornames: ^0.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  uuid: ^4.4.0
  # package_info_plus: ^8.0.0
  # flutter_native_splash: ^2.4.1
  permission_handler: ^12.0.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  objectbox_generator: any
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.5
flutter:
  uses-material-design: true
